lab06/graphy/config/routes.rb
Threeactionsproject::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'dashboard' => 'dashboard#view'

  resources :action_plans
  resources :users do
    resources :user_action_items do
      resources :ratings
    end
  end

  match 'results/:user_id' => 'results#fetch'

end

lab06/graphy/app/models/action_category.rb
class ActionCategory < ActiveRecord::Base
  attr_accessible :name
  has_many :action_items
end

lab06/graphy/app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  attr_accessible :description, :name, :action_category_id
  belongs_to :action_category
  has_many :user_action_items
  has_many :users, :through => :user_action_items
end

lab06/graphy/app/models/action_rating.rb
class ActionRating < ActiveRecord::Base
  belongs_to :action_item
  belongs_to :user
  attr_accessible :cons, :pros, :rating
end

lab06/graphy/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

lab06/graphy/app/models/metric.rb
class Metric < ActiveRecord::Base
  attr_accessible :cons, :description, :max_rating, :min_rating, :name, :pros
  has_many :ratings
  has_many :user_action_items, :through => :ratings
end

lab06/graphy/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user_action_item
  belongs_to :metric
  scope :for_user, lambda { |user_id|
    includes(:user_action_item).includes(:metric).where('user_action_items.user_id' => user_id).order(:week_number)
  }
  # attr_accessible :title, :body
end

lab06/graphy/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :facebook_uid, :photo_url
  # attr_accessible :title, :body

  has_many :user_action_items
  has_many :action_items, :through => :user_action_items
  has_many :user_relationships
  has_many :friends, :through => :user_relationships

  def self.find_for_facebook_oauth omniauth, user
    logger.warn "OMNIAUTH: #{omniauth.to_json}"
    logger.warn "OMNIAUTH: #{omniauth['uid']}"
    logger.warn "OMNIAUTH: #{user}"
    user = User.find_by_facebook_uid(omniauth['uid'])
    if user.nil?
      # create new user based on login
      user = User.create({ :first_name => omniauth[:info][:first_name], 
                           :last_name => omniauth[:info][:last_name],
                           :facebook_uid => omniauth[:uid],
                           :email => omniauth[:info][:email],
                           :photo_url => omniauth[:info][:image],
                           # Don't really _NEED_ a password, but this will let us
                           # save the model
                           :password => omniauth[:credentials][:token]
                         })
      user.save!
    end
    user
  end

  def add_item_if_new action_item
    self.action_items << action_item unless self.action_items.include? action_item
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

lab06/graphy/app/models/user_action_item.rb
class UserActionItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :action_item
  has_many :ratings
  has_many :metrics, :through => :ratings
  accepts_nested_attributes_for :ratings
  def rating_for metric, week
    self.ratings.detect { |r| r.metric == metric && r.week_number == week }
  end
end

lab06/graphy/app/models/user_relationship.rb
class UserRelationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

lab06/graphy/app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_filter :authenticate_user!
  def add
    item = ActionItem.find(params[:id])
    current_user.add_item_if_new item
    redirect_to action_plans_url
  end
end

lab06/graphy/app/controllers/action_plans_controller.rb
class ActionPlansController < ApplicationController
  before_filter :authenticate_user!
  def index
    @action_plan = current_user.action_items
    @action_categories = ActionCategory.all
  end
end

lab06/graphy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lab06/graphy/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def view
    # ObjectSpace.each_object do |s|
      # not actually doing anything in here.  Just laying a trap
    # end
    @action_plan = current_user.user_action_items
    @metrics = Metric.order(:name).all
  end
end

lab06/graphy/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authenticate_user!
  def fetch
    requested_id = params[:user_id]
    u = current_user.id
    if has_access(current_user, requested_id)
      ratings = Rating.for_user(requested_id)
      logger.debug(ratings.to_json)
      ratings_by_metric = {}
      ratings.each do |r|
        ratings_by_metric[r.metric.name] = [] unless ratings_by_metric[r.metric.name]
        ratings_by_metric[r.metric.name] << r
      end
      results = []
      ratings_by_metric.each_pair do |name, ratings|
        rec = { :metric => name, :ratings => ratings.map { |r| [r.week_number, r.value] } }
        results << rec
      end
      render :json => results.to_json
    else
      render :json => [].to_json
    end
  end

  private
  def has_access user, friend_id
    return true
    user.friends.any? { |f| f.id == friend_id }
  end
end

lab06/graphy/app/controllers/user_action_items_controller.rb
class UserActionItemsController < ApplicationController
  before_filter :authenticate_user!
  def update
    user_action_items = params[:user_action_item]
    week_number = params[:week_number]
    user_action_items.each_pair do |key, ratings|
      logger.debug "Week: #{week_number}; Action Item #{key}: #{ratings.to_json}"
      uai = UserActionItem.where(:user_id => current_user.id).find(key)
      Rating.delete(Rating.where(:user_action_item_id => uai).where(:week_number => params[:week_number]).all)
      ratings.each do |rating|
        logger.debug "Rating: #{rating.to_json}; metric: #{Metric.find(rating.first).id}"
        r = Rating.new
        r.user_action_item = uai
        r.week_number = week_number
        r.metric = Metric.find(rating.first)
        r.pros = rating.second["pros"]
        r.cons = rating.second["cons"]
        r.value = rating.second["value"]
        uai.ratings << r
      end
    end
    render(:json => { :result => "success" }.to_json)
  end
end

lab06/graphy/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    logger.warn "OMNIAUTH: #{request.env["omniauth.auth"].to_json}"
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end    
  end
end

lab06/graphy/app/helpers/action_items_helper.rb
module ActionItemsHelper
end

lab06/graphy/app/helpers/action_plans_helper.rb
module ActionPlansHelper
end

lab06/graphy/app/helpers/application_helper.rb
module ApplicationHelper
end

lab06/graphy/app/helpers/dashboard_helper.rb
module DashboardHelper
end

lab06/graphy/app/helpers/results_helper.rb
module ResultsHelper
end

lab06/graphy/app/views/action_plans/index.html.erb
<h2>Your Action Plan</h2>

<div class="action_plan">
  <% if @action_plan.empty? %>
  <p>You haven't created an action plan yet.</p>
  <% else %>
    <ul>
    <% @action_plan.each do |item| %>
      <li><%= item.name %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<h2>Available Action Items</h2>
<% @action_categories.each do |category| %>
<div class="action_category">
  <h3><%= category.name %></h3>
  <ul>
    <% category.action_items.each do |item| %>
    <li><%= link_to item.name, add_action_item_path(item) %></li>
    <% end %>
  </ul>
</div>
<% end %>

lab06/graphy/app/views/dashboard/view.html.erb
<div id="action_tracker">
  <%= image_tag current_user.photo_url if current_user.photo_url %>
  User ID: <%= current_user.id %>
  <% if @action_plan.nil? %>
    <%= link_to "Create Action Plan", new_user_action_plans_path %>
  <% else %>
    <div id="weeks">
      <ul>
        <% 1.upto(8).each do |week| %>
        <li><a href="#weeks-<%= week %>">Week <%= week %></a></li>
        <% end %>
      </ul>
      <% 1.upto(8).each do |week| %>
        <% @action_plan.each do |item| %>
          <div id="weeks-<%= week %>" class="action_item_rating">
            <%= form_for([current_user, item], :remote => true) do |f| %>
              <%= hidden_field_tag(:week_number, week) %>
              <div>Week <%= week %>: Rate your week with <%= item.action_item.name %></div>
              <% @metrics.each do |metric| %>
                <div class="action_item_rating_metric">
                  <%= render :partial => "shared/metric_rating", :locals => {
                  :f => f,
                  :metric => metric,
                  :action_item => item,
                  :rating => item.rating_for(metric, week)
                  } %>
                </div>
              <% end %>
              <div><%= submit_tag %></div>
            <% end %>
          </div>
        <% end %>
     <% end %>
    </div>
  <% end %>
</div>
<% unless current_user.friends.empty? %>
<% content_for :sidebar do %>
<div class="self">
  <div>How are you doing?</div>
  <div id="user-plot-<%= current_user.id %>" class="user-plot" data-user="<%= current_user.id %>">
  </div>
    <div id="user-plot-legend-<%= current_user.id %>" class="user-plot-legend" data-user="<%= current_user.id %>">
    </div>
</div>
<div class="cohorts">
  <div>How are your <em>cohorts</em> doing?</div>
  <% current_user.friends.each do |cohort| %>
  <div class="cohort">
    <div class="user-name"><%= cohort.full_name %></div>
    <div id="user-plot-<%= cohort.id %>" class="user-plot" data-user="<%= cohort.id %>">
    </div>
    <div id="user-plot-legend-<%= cohort.id %>" class="user-plot-legend" data-user="<%= cohort.id %>">
    </div>
  </div>
  <% end %>
</div>
<% end %>
<% end %>